# Generated by Django 3.2 on 2021-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_capacity', models.IntegerField()),
                ('consumables', models.CharField(max_length=100)),
                ('cost_in_credits', models.IntegerField()),
                ('crew', models.IntegerField()),
                ('length', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=500)),
                ('max_atmosphering_speed', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('passengers', models.IntegerField()),
                ('hyperdrive_rating', models.FloatField()),
                ('url', models.CharField(default=None, max_length=100)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('starship_class', models.CharField(max_length=100)),
                ('MGLT', models.CharField(max_length=100)),
                ('sell_price', models.IntegerField()),
                ('condition', models.CharField(choices=[('Bucket', 'Bucket'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Like New', 'Like New')], default='Good', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('mileage', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
