# Generated by Django 3.2 on 2021-04-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.craft')),
            ],
        ),
    ]
